server {
    listen 80;
    server_name localhost;

    # Serve the React application from the /my-portfolio/ path
    location /my-portfolio/ {
        alias /usr/share/nginx/html/my-portfolio/;
        try_files $uri $uri/ /my-portfolio/index.html;
    }

    # Redirect root traffic to the portfolio
    location = / {
        return 301 /my-portfolio/;
    }

    # Optional: Error pages
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
